### ISSUE TITLE
Remote save error

### ISSUE THREAD

**Issue by jxxcarlson** [HubPress/hubpress.github.io#7]
Probably a misconfiguration on my part, but when I save a blog post at http://jxxcarlson.github.io/noteshareblog.github.io/hubpress, I get the error

```
Remote save
An error has occurred, see your console for more informations.
```

I don't see any furhter information in the console.

PS. It should be "information", not "informations" :-)

**Comment by anthonny** [comment]
Hi James,

In your config.json file, repositoryName must be *noteshareblog.github.io
<http://noteshareblog.github.io>*

Le mer. 1 avr. 2015 à 14:56, James Carlson <notifications@github.com> a
écrit :

**Comment by anthonny** [comment]
Hi James,

In your config.json file, repositoryName must be **noteshareblog.github.io**

And you must set the branch **gh-pages** as default branch in the settings of the repository

**Comment by jxxcarlson** [comment]
Hi Anthony,

  My bad — all working now — I had the correct json file in the correct branch
but had not set gh-pages as the default branch.

**Comment by jaredmorgs** [comment]
Hmm, that error message was fixed in the latest HubPress release. You
should consider updating your instance following the instructions in the
README.adoc in the HubPress Master repository. There is a video I made
showing how to do this correctly.

**Comment by jxxcarlson** [comment]
I did a compare and seem to be up to date.  ??? 
In any case, I forked this morning, so I must be
pretty close to recent.

Jim

http://noteshare.io

**Comment by jxxcarlson** [comment]
Ir there is a way to delete my hubpress account, I could just start over —
only have one page of note and I have the source on my laptop.

Jim

http://noteshare.io

**Comment by anthonny** [comment]
You haven't a HubPress account :), you have a copy of HubPress so you can do everything you want.

IMHO, the best solution is to save locally your blog post, delete your repository **jxxcarlson.github.io** (in the settings of the repository), then fork again the **hubpress.io** repository.

Then, you can rename your fork to **jxxcarlson.github.io** and set your config.json

**Comment by jxxcarlson** [comment]
Worked like a charm! 5 min from start to finish!!

**Comment by anthonny** [comment]
Good news! :beers:
